import file from "@/data/evidence.json";
import { canDisplay } from "./format";
import type { EvidencePoint, ResearchQuestionId, VisualizationData } from "./types";

/**
 * Typed access to `data/evidence.json`, which is generated by
 * `research/build_evidence.py` (run `npm run data:build`). Never edit the JSON
 * by hand: edit `research/evidence.jsonl` and rebuild.
 */
export const evidence: EvidencePoint[] = file.evidence as EvidencePoint[];

const byId = new Map(evidence.map((e) => [e.id, e]));

/** Looks up an evidence point. An unknown id fails the build rather than rendering nothing. */
export function getEvidence(id: string): EvidencePoint {
  const point = byId.get(id);
  if (!point) throw new Error(`Evidence not found: ${id}`);
  return point;
}

export function evidenceFor(rq: ResearchQuestionId): EvidencePoint[] {
  return evidence.filter((e) => e.rq.includes(rq));
}

export interface ResolvedVisualization extends VisualizationData {
  /** Verified points, in the order given. */
  points: EvidencePoint[];
  /** Points held back because they are not verified yet. */
  withheld: EvidencePoint[];
}

/**
 * Resolves a chart's evidence ids and enforces chart-level integrity rules:
 * every id must exist, and when `sharedBase` is set, every point must have
 * exactly that respondent base (so a chart can never mix denominators).
 */
export function resolveVisualization(spec: VisualizationData): ResolvedVisualization {
  const all = spec.evidenceIds.map(getEvidence);
  if (spec.sharedBase !== null) {
    const mismatched = all.filter((p) => p.base !== spec.sharedBase);
    if (mismatched.length) {
      throw new Error(
        `${spec.id}: mixed respondent bases (${mismatched.map((p) => `${p.id}: ${p.base}`).join("; ")})`,
      );
    }
  }
  return {
    ...spec,
    points: all.filter(canDisplay),
    withheld: all.filter((p) => !canDisplay(p)),
  };
}
